// <auto-generated />
using HQY_Microservice.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HQY_Microservice.Migrations
{
    [DbContext(typeof(MemberContext))]
    partial class MemberContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HQY_Microservice.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            Email = "mark.wilson@xyz.com",
                            FirstName = "Mark",
                            LastName = "Wilson",
                            PhoneNumber = "916-346-7839"
                        },
                        new
                        {
                            MemberId = 2,
                            Email = "ted.parker@xyz.com",
                            FirstName = "Ted",
                            LastName = "Parker",
                            PhoneNumber = "916-326-7839"
                        },
                        new
                        {
                            MemberId = 3,
                            Email = "lynn.johnson@xyz.com",
                            FirstName = "Lynn",
                            LastName = "Johnson",
                            PhoneNumber = "516-896-3439"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
